language: java
jdk:
- openjdk11
notifications: ekrempnar@gmail.com
addons:
  sonarcloud:
    organization: ekrempnar
    token:
      secure: fdsTUcNsRXiSQ2BDWSy/zzsa5ldsQQzlF/asULwq3IlvoH1wYuJA5ltSULPmd3M8akjLw7hro5CH4DG93q9D92VYtrFZ094ucN4ND7os5lEGYOXVkXp/YL8ZdxYN9E6dEHWfcsYTVIKz51JGDcs+vrH0sZm+X6HGtyMtSv8HIREz5HQm3F6hG25sMMLMjzhtPVugtG4APcD65fVOgmgHBvphPYTXnklsZnU5Iwgxhrn0FP3kPw9XBG58bkf65H6lhuVXb+MZQuRsNCHbq0CR98E5b2q+ZX6Z95MRF/TxOHSa//ipdpdyW69hwrGP7W99VkeGt9A/BxPwGGFuuem2Hnh/o32Lm/1ulKpMJQVqwL7thHlwN8XqR/PvHDz/8DI0S89sIQvTDLsj2qdu/ApnuhMsCq6oAgg2uROSdK2n2ASFydb3hElOOaGFz0S8u6Nu1BhXakgLgJbiTrRJSfY2d40tZkU7kZDwSyxs7V6g29nGWhlDCv+uFkzCsKgkjP3YhCyMfpuvnMwnG8o4QLtVoD+bzePDD56bP5taqETbXENiOiLc3I32K28QKzKtzirrywNe4eBwrE+rgklRe2spmNLi3wvIt1I+6J8yYocL8K8RE5EZL2js8dgBGMaNP28eNRWZQX1Gf1v4+R89PZp6yvquLCcd+ae0YoYHP6/7eSU=
script:
- sonar-scanner
env:
  global:
    secure: m+0VRZ3UNLK2Tb5zrtbos3tGKOJXuY6nEH/V4tUOYut12HYj96Ix60MjUX2bo9sI48YKwVXhs3DUDrf1cOXX6sEHwrVLyPcaV2dN89lD/7W9gmOoxyU3U3K6cIWnj893kPsky5O5gSzjYqg7FCcaIb/H3jHQtOAZTcv0sCpEaqOQtvq/s1E8xneffC8CDqO3r9C3tIENJElFqLu6ZB2HgGVwV7whrw0+VRdQeHBKf3YUpw0I7ed1uHbnf5JinKS+piCXNPgnjBnzGXxZx9ykIl1P5TvfFTP1UwOWyVGD64gi8IvuErodLLPSSY5pd8Pf0lAFXKJ+5LSKRi8jcbwvPk0Dp1IdugfQZpPg1Phk5wHiMCgIuQSIPjOSLN43i3Q92my6RFpR0H3Ayi6ENq3QxbrMzdisMHJl9DIUNWWuxA/UESCh6lj2oSBkgJRCztSjvd80SpMxNklF0sJj+C/aC5j6h/ffP9UIrYDmmyw5Wl2fzhxTDNijfF2AesMzHSLOXo7mFUfQNK4ygd3h2LnFu0ahGaF3Se7AmTgbQB2CSUJryT4uuDG3sgQ79moRBAGWSKwKc6TtCnAQzyhUQrBTAZLKtNiwkrNmtaEuQ7neLbJykCyn0OSDlnSZhZ1nham0eIow80q0oUYErBj9Ilebki6wR9k4WkH/D2lkYcNuYaE=
