language: java
jdk:
  - openjdk11
notifications:
  ekrempnar@gmail.com

addons:
  sonarcloud:
    organization: "ekrempnar" # the key of the org you chose at step #3
    token:
      secure: "OPGL7h7FWb74X/gWljrO3xg3gvv5315OQ0zgCcILnWZEFT8r3mPpHTsP3BinPUAzWSfxKCQrl/6f/dGULwrYwhlF1JNu4CZF7Y5ZCcr1ydghWDyaT28w3fCFl+xj9hV5RiO6v+0i/xPkhutRiC0L0pD6tEYhEzid8YG28R7ZuTGYzlMNlDVOT+OLrI6Lzhozibf7gJcpuOjqgwomCK/igNw+C5BbNUZ0W+anIWJ6Aj3gdZHyjxAzClzsldFzp4JPMJyftEQy7Q4F4kaKq62Ye077fi+3i2NU1nH6bUF/qtdYH1xgjwLWrHv4DXzuSZBMGHdC/h04HNIlsg+7/zK4rU+DzTUaIJy3XTvY57VbBo50edUm2wS524wg0+05tQUhdpB6DqwbveeukliSvfjqKRTVMgGpCY2kt/Pw6lXSu+B4WYAj+q38rpf8rF1xIqHgghTQO+YvErDk/Fn5MRNfolH88x8Fv2cGgGVS2E9YYvYYySYgriy3SiaJWf24vufwXUw9zYZoKn9McTbmgVjxT3HSpk3YlWeYZNbOn4RJSnDf0NNuaWfS3fxwACMq17b7Y05YrthxbNzjRnOjjrk6Zgjr4FGBya+EHjmaPwaEiLCIaOZPlGkTFwUEVzBY4LkohPZiykhiS4y8/1E/0Zjm0Tmi7Uql5M7KvsclnwCSjoA="
  # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner