addons:
  sonarcloud:
    organization: "ekrempnar" # the key of the org you chose at step #3
    token:
      secure: "FTJM1CP0PXDNoQptrdZhRNNUQqu1soNQBcPf/dxsBjpyzlsNMu1cdn7d7TryWzPr+RpRJw/HeGrvJ2Szm1NLv2f06yxQCBZx2Dze5rX/Mza3fZ3kZApVsAZMckyLZJmjItTeZJIj5ef+vpp0ySXNbf+gujjr4XCr5oR3L7HlxDQ3pozbcxOr7dLk0fUcPYsSQ04ioI6e+jfZZRSQa8UCb3XVq6M4zo9OvaSwmZvIl8854UDmS53p4QIbk0hMv2slj1LPXxhq1pIv/hWwQIfAc8fxARTgquXWQUDFMcAcqGnXxe8Mt5izRPTF7Ohq5VZCB84ye2dYhbanA51I55i7Sakk2kG3ObpYwUCKvTRknSZHAcucBtD6qEvSU1TpG5jjsY5lIwi2pdxapWKFffT+KZwy5M2byybyrAMQ4CUX0IMqBVpcotHxJzePcfBUP7pjQ1+5m2aHqRi9pkHJ2LuAZbMcUXb/TrrMS0GzmYQwfDeC+sLo1jamezcKWCJWqiCreIkCF3r5HgKqLSW7HMuwcdSs2n+tMrkGSJOKAT/9sC2lpAXUlyO9DVLKtvIHziwVwiBwntrVGn8vPoL2jZEHQMY6AvGjqf83udStJuU6dZTJuvm0XzQPelqxav0IinPkN5++VN66zNAS7wBFhW3wtmsswBmy29LDbGp+5xaktl8="
  # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ekrempnar_ant-media-first-case