addons:
  sonarcloud:
    organization: "ekrempnar" # the key of the org you chose at step #3
    token:
      secure: "SJ2JxSHuk/MDBVwYWw5QcIObKo/znN39hLTpWvm4LbfCEQLpOFYeBTrpqS6Iz7oUpfzJ87XqxGWCj5Z7w24I5u8IKL9pb9xup0XonocKCqAa5xqapDH3UBt+IzAbIc7ueyrv7FRlWdXMD1Z10eEaqwKx4FZUg2dxAFbuReCZVWxX12hP0msc4GTw+oD7bsK7cbk/6snAKnX6ouAbioAGPXyFi5Gg+NHr6CsidazsgJLgfm2ummvJ8AaxMPeVn+bEmUrALvjnJeVeYUbH7jl2YSBhjJohrcT2s1vKUGjvNisxNFRU8qSjdZqSFFj02MSTbdcyYG03DpvYr/YFSgcXPjtjspQyCP6xvmeTC0EUYgkbAeR2Opgz5M17avKv94Y52FvY9xWPow3/RWWTFuSVx27Lisn7qtHQkiV3QIx6tKBELXNP1j6kUHdxGXf38JeKsPfRpY+ZuK/y+4/7kxL+vYas7RQbPXQN/ksEqxJLjmzCbrbDeHTdVWckvnZ3r2JLcM27og+EghS753l3EXIPcdfasFKKcrvKGHgzsHCtq8Wcq0f4gfVdSA8jGep957icdsP4gNRk5UMO3S3yhcSt5ce8F6dP5z8Vu/gFanaorJC4LFxTLYuSjws37Sqcr1iOpO5mfO5oCaRoGwIRuteDVRpKr376kWXSVZvO3GwST3M="
  # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ekrempnar_ant-media-first-case