language: java
jdk:
  - openjdk11
notifications:
  ekrempnar@gmail.com

addons:
  sonarcloud:
    organization: "ekrempnar" # the key of the org you chose at step #3
    token:
      secure: "fdsTUcNsRXiSQ2BDWSy/zzsa5ldsQQzlF/asULwq3IlvoH1wYuJA5ltSULPmd3M8akjLw7hro5CH4DG93q9D92VYtrFZ094ucN4ND7os5lEGYOXVkXp/YL8ZdxYN9E6dEHWfcsYTVIKz51JGDcs+vrH0sZm+X6HGtyMtSv8HIREz5HQm3F6hG25sMMLMjzhtPVugtG4APcD65fVOgmgHBvphPYTXnklsZnU5Iwgxhrn0FP3kPw9XBG58bkf65H6lhuVXb+MZQuRsNCHbq0CR98E5b2q+ZX6Z95MRF/TxOHSa//ipdpdyW69hwrGP7W99VkeGt9A/BxPwGGFuuem2Hnh/o32Lm/1ulKpMJQVqwL7thHlwN8XqR/PvHDz/8DI0S89sIQvTDLsj2qdu/ApnuhMsCq6oAgg2uROSdK2n2ASFydb3hElOOaGFz0S8u6Nu1BhXakgLgJbiTrRJSfY2d40tZkU7kZDwSyxs7V6g29nGWhlDCv+uFkzCsKgkjP3YhCyMfpuvnMwnG8o4QLtVoD+bzePDD56bP5taqETbXENiOiLc3I32K28QKzKtzirrywNe4eBwrE+rgklRe2spmNLi3wvIt1I+6J8yYocL8K8RE5EZL2js8dgBGMaNP28eNRWZQX1Gf1v4+R89PZp6yvquLCcd+ae0YoYHP6/7eSU="
  # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner